#name: Android Build
#
#on:
#  push:
#    branches:
#      - master  # Change this to the branch you want to trigger the build on (e.g., master)
#
#jobs:
#  build:
#    name: Build Android App Bundle
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup Java
#        uses: actions/setup-java@v2
#        with:
#          distribution: "zulu"
#          java-version: "12.x"
#          cache: 'gradle'
#      - name: Setup Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: "3.7.10"
#          channel: 'stable'
#          cache: true
#      - name: ðŸ“ðŸ” Create keystore.properties file
#        run: |
#          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
#          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> android/key.properties
#          echo "keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> android/key.properties
#          echo "storeFile=keystore.jks" >> android/key.properties
#
#      - name: ðŸ” Retrieve base64 keystore and decode it to a file
#        run: |
#          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks
#          chmod +x android/app/keystore.jks
#      - name: Verify JKS File
#        run: |
#          if [ -f "android/app/keystore.jks" ]; then
#            echo "JKS file created successfully!"
#          else
#            echo "Failed to create JKS file!"
#            exit 1
#          fi
#
#      - name: Build Android App Bundle
#        run: flutter build appbundle
#
#      - name: Save Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: app-bundle
#          path: build/app/outputs/bundle/release/app-release.aab
