name: Android Build

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the build on (e.g., master)

jobs:
  build:
    name: Build Android App Bundle
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12.x"
          cache: 'gradle'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.10"
          channel: 'stable'
          cache: true
#      - name: ðŸ” Retrieve base64 keystore and decode it to a file
#        env:
#          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
#        run: echo $KEYSTORE_BASE64 | base64 --decode > "${{ github.workspace }}/android-keystore.jks"
#      - name: Create the Keystore
#        env:
#          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
#        run: |
#          # import keystore from secrets
#          echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.jks
#      - name: ðŸ“ðŸ” Create keystore.properties file
#        env:
#          KEYSTORE_PROPERTIES_PATH: ${{ github.workspace }}/app/android/keystore.properties
#        run: |
#          touch ${{ github.workspace }}/app/android/keystore.properties
#          echo '${{ inputs.flavor }}StoreFile=${{ github.workspace }}/android-keystore.jks' > ${{ github.workspace }}/app/android/keystore.properties
#          echo '${{ inputs.flavor }}KeyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}' >> ${{ github.workspace }}/app/android/keystore.properties
#          echo '${{ inputs.flavor }}StorePassword=${{ secrets.KEYSTORE_PASSWORD }}' >> ${{ github.workspace }}/app/android/keystore.properties
#          echo '${{ inputs.flavor }}KeyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}' >> ${{ github.workspace }}/app/android/keystore.properties
#        run: |
#          echo keyPassword=\${{ secrets.KEYSTORE_KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
#          echo storePassword=\${{ secrets.KEYSTORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
#          echo keyAlias=\${{ secrets.KEYSTORE_KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
      - name: ðŸ“ðŸ” Create keystore.properties file
        run: |
          echo "storePassword=omar123" >> android/key.properties
          echo "keyPassword=omar123" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: ðŸ” Retrieve base64 keystore and decode it to a file
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks
          chmod +x android/app/keystore.jks
      - name: Verify JKS File
        run: |
          if [ -f "android/app/keystore.jks" ]; then
            echo "JKS file created successfully!"
          else
            echo "Failed to create JKS file!"
            exit 1
          fi

      - name: Build Android App Bundle
        run: flutter build appbundle

      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab
