name: Android Build

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the build on (e.g., master)

jobs:
  build:
    name: Build Android App Bundle
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12.x"
          cache: 'gradle'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.10"
          channel: 'stable'
          cache: true
#      - name: ðŸ” Retrieve base64 keystore and decode it to a file
#        env:
#          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
#        run: echo $KEYSTORE_BASE64 | base64 --decode > "${{ github.workspace }}/android-keystore.jks"
      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.jks
#      - name: ðŸ“ðŸ” Create keystore.properties file
##        env:
##          KEYSTORE_PROPERTIES_PATH: ${{ github.workspace }}/app/android/keystore.properties
#        run: |
#          touch ${{ github.workspace }}/app/android/keystore.properties
#          echo '${{ inputs.flavor }}StoreFile=${{ github.workspace }}/android-keystore.jks' > ${{ github.workspace }}/app/android/keystore.properties
#          echo '${{ inputs.flavor }}KeyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}' >> ${{ github.workspace }}/app/android/keystore.properties
#          echo '${{ inputs.flavor }}StorePassword=${{ secrets.KEYSTORE_PASSWORD }}' >> ${{ github.workspace }}/app/android/keystore.properties
#          echo '${{ inputs.flavor }}KeyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}' >> ${{ github.workspace }}/app/android/keystore.properties
#      - name: Build Android App Bundle
#        run: flutter build appbundle
      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Sign Android App Bundle
        run: jarsigner -keystore $RUNNER_TEMP/my_production.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEYSTORE_PASSWORD_ALIAS }} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/release/app-release-signed.aab build/app/outputs/bundle/release/*.aab my_production_alias


      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab
